FROM mcr.microsoft.com/dotnet/core/sdk:3.0-buster-arm32v7 as build
EXPOSE 80

COPY RightmoveDownloader /RightmoveDownloader
WORKDIR /RightmoveDownloader
RUN dotnet publish -o /app

FROM mcr.microsoft.com/dotnet/core/aspnet:3.0-buster-slim-arm32v7 as final
COPY --from=build /app /app
WORKDIR /app
RUN sed -i '/^CipherString/d' /etc/ssl/openssl.cnf

ENTRYPOINT ["dotnet", "RightmoveDownloader.dll"]